Temporarily fix pysam on 0.7.8 (0.8.0 fails on Python 3)
Before we figure out what causes this, let's have a working test suite by
fixing pysam on the latest working release.

Traceback:

    Traceback (most recent call last):
      File "/home/travis/build/jamescasbon/PyVCF/build/lib.linux-x86_64-3.3/vcf/test/test_vcf.py", line 1109, in testNoVariantsInRange
        fetched_variants = self.reader.fetch('20', 14370, 17329)
      File "/home/travis/build/jamescasbon/PyVCF/build/lib.linux-x86_64-3.3/vcf/parser.py", line 623, in fetch
        self.reader = self._tabix.fetch(chrom, start, end)
      File "ctabix.pyx", line 345, in pysam.ctabix.Tabixfile.fetch (pysam/ctabix.c:4241)
    TypeError: expected bytes, str found

See #175